<?php
echo '<img src="profile.jpg"   width="250" height="250" /> <h1>'.$row1["doc_name"].'</h1><p class="title">'.$row1["specialisation"].'</p><b><p>'.$username.'</p></b><div style="margin: 24px 0;"><a href="#"><i class="fa fa-dribbble"></i></a> <a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-linkedin"></i></a>    <a href="#"><i class="fa fa-facebook"></i></a> </div><p><button onclick="">Get OP</button></p></div></body></html>' ; 



/*echo '<img src="data:image/jpeg;base64,' .base64_encode($row['image']) . ' "   width="250" height="250" /> <h1>'.$row["username"].'</h1><p class="title">CEO & Founder, TechyMan</p><b><p>Harvard University</p></b><div style="margin: 24px 0;"><a href="#"><i class="fa fa-dribbble"></i></a> <a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-linkedin"></i></a>    <a href="#"><i class="fa fa-facebook"></i></a> </div><p><button onclick="">Get OP</button></p></div></body></html>' ; */

echo '<!DOCTYPE html><html><head><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"><style>.card {box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);max-width: 300px;margin: auto;  text-align: center;font-family: arial;}.title {color: grey;font-size: 18px;}button {order: none;outline: 0;display: inline-block;padding: 8px;color: white;background-color: #000;text-align: center;cursor: pointer;width: 100%;font-size: 18px;}a {text-decoration: none;font-size: 22px;color: black;}button:hover, a:hover {opacity: 0.7;}</style></head><body ><h2 style="text-align:center">Doctor Profile Card</h2><div class="card"><img src="profile.jpg"   width="250" height="250" /> <h1>'.$row1["doc_name"].'</h1><p class="title">'.$row1["specialisation"].'</p><b><p>'.$username.'</p></b><div style="margin: 24px 0;"><a href="#"><i class="fa fa-dribbble"></i></a> <a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-linkedin"></i></a>    <a href="#"><i class="fa fa-facebook"></i></a> </div><p><button onclick="">Get OP</button></p></div></body></html>' ;


?>